# Was by-default here
spring.application.name=AI Trading

# backend-frontend interaction
app.cors.allowed-origins = ${APP_CORS_ALLOWED_ORIGINS}

###### Connect app to database :- ######

spring.datasource.username = ${db_USERNAME}
spring.datasource.password= ${db_PASSWORD}
# ___URL contains -
# ___DB type : mysql
# ___DB host : aiven-db-first.....aivencloud.com
# ___DB port no. : 18..
# ___DB name : cryp..
spring.datasource.url = ${db_URL}
#spring.datasource.url=jdbc:h2:mem:Crypto

# ___specific JDBC driver class name that helps to communicate with db
spring.datasource.driver-class-name = com.mysql.cj.jdbc.Driver
#spring.datasource.driverClassName = org.h2.Driver
# ___for GUI view of the database
#spring.h2.console.enabled = true

###### JPA and Hibernate config (while handling database) :- ######

# ___ddl-auto -> tells how 'hibernate' (ORM tool of jpa) should handle db schema [with DDL commands]
spring.jpa.hibernate.ddl-auto = create-drop
# ___log sql statements in console ?
spring.jpa.show-sql = true

# ___formats the SQL nicely so it isn't crammed onto one line
spring.jpa.properties.hibernate.format_sql=true

# ___shows the actual data values (bind parameters) instead of '?'
logging.level.org.hibernate.orm.jdbc.bind=trace

###### API keys :- ######

# ___for Payment -
stripe.api.key = ${STRIPE_API_KEY}
razorpay.api.key = ${RAZORPAY_API_KEY}
razorpay.api.secret = ${RAZORPAY_SECRET_KEY}

# ___for Crypto monitoring -
coingecko.api.key= ${COIN-GECKO_API_KEY}

# ___for Chatbot assistant -
gemini.api.key = ${GEMINI_API_KEY}


####### Java mail service (using Gmail SMTP) :- ######

# ___SMTP Host (e.g. Gmail)
spring.mail.host = ${MAIL_HOST}
spring.mail.port= ${MAIL_PORT}

# ___email credentials
spring.mail.username = ${MAIL_USERNAME}
spring.mail.password = ${MAIL_PASSWORD}

# ___SMTP mail server will require authentication for sending e-mails
spring.mail.properties.mail.smtp.auth=true

# ___for secure, encrypted TLS connection using the STARTTLS command
spring.mail.properties.mail.smtp.starttls.enable=true

# ___for enforcing strict security by making the TLS encryption mandatory
spring.mail.properties.mail.smtp.starttls.required=true